spring.application.name=event-management-system

spring.jpa.generate-ddl=true
spring.datasource.url=jdbc:postgresql://localhost:5006/postgres
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

secret.key=secret123

